MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
SiteTitle: My Blog
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
PostSources: posts/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml